DROP TABLE IF EXISTS hebergements ;
CREATE TABLE hebergements AS

WITH hebergements AS

(SELECT id,
       'Hébergements collectifs'::varchar AS nature,
       nomoffre,
       acces,
       acceshandi,
       activplace,
       animaux,
       NULL::varchar AS chaines,
       NULL::varchar AS clas,
       NULL::varchar AS modgest,
       gestrsociale,
       commune,
       communeinsee,
       'Aquitaine'::varchar AS region,
       confort,
       cp,
       descriptifmob,
       equip,
       formuleheb,
       groupe,
       groupemax,
       groupemin,
       labels,
       labelsclas,
       localisation,
       mail,
       modpaiement,
       NULL::int AS capa,
       NULL::int AS capaclas,
       nbrelogements,
       NULL::int AS nbrelogclas,
       NULL::int AS nbrelogpmr,
       nbrelits,
       NULL::int AS nbrelitsclas,
       NULL::int AS nbrechamb,
       NULL::int AS nbrechambclas,
       NULL::int AS nbrechambfami,
       NULL::int AS nbrechambpmr,
       ouverture,
       ouvertureavecjours,
       ouverturedates,
       services,
       tel,
       typehco,
       typelogements,
       url,
       'PIGMA'::text AS SOURCE,
       'https://www.pigma.org/portail/fr/jeux-de-donnees/aquitaine_hebergements_collectifs/info'::text AS source_url,
       geom
FROM public.hebergement_collectifs
UNION ALL
SELECT id,
       'Hôtels'::varchar AS nature,
       nomoffre,
       acces,
       acceshandi,
       activplace,
       animaux,
       chaines,
       clas,
       NULL::varchar AS modgest,
       NULL::varchar AS gestrsociale,
       commune,
       communeinsee,
       'Aquitaine'::varchar AS region,
       confort,
       cp,
       descriptifmob,
       equip,
       NULL::varchar AS formuleheb,
       groupe,
       groupemax,
       groupemin,
       NULL::varchar AS labels,
       NULL::varchar AS labelsclas,
       localisation,
       mail,
       modpaiement,
       NULL::int capa,
       NULL::int capaclas,
       NULL::int AS nbrelogements,
       NULL::int AS nbrelogclas,
       NULL::int AS nbrelogpmr,
       nbrelits,
       nbrelitsclas,
       nbrechamb,
       nbrechambclas,
       nbrechambfami,
       nbrechambpmr,
       ouverture,
       ouvertureavecjours,
       ouverturedates,
       services,
       tel,
       typehot,
       NULL::varchar AS typelogements,
       url,
       'PIGMA'::text AS SOURCE,
       'https://www.pigma.org/portail/fr/jeux-de-donnees/aquitaine_hotels/info'::text AS source_url,
       geom
FROM public.hotels
UNION ALL
SELECT id,
       'Résidence tourisme'::varchar AS TYPE,
       nomoffre,
       acces,
       acceshandi,
       activplace,
       animaux,
       chaines,
       clas,
       NULL::varchar AS modgest,
       NULL::varchar AS gestrsociale,
       commune,
       communeinsee,
       'Aquitaine'::varchar AS region,
       confort,
       cp,
       descriptifmob,
       equip,
       NULL::varchar AS formuleheb,
       groupe,
       groupemax,
       groupemin,
       NULL::varchar AS labels,
       NULL::varchar AS labelsclas,
       localisation,
       mail,
       modpaiement,
       NULL::int AS capa,
       NULL::int AS capaclas,
       nbrelog,
       nbrelogclas,
       nbrelogpmr,
       nbrelits,
       nbrelitsclas,
       NULL::int AS nbrechamb,
       NULL::int AS nbrechambclas,
       NULL::int AS nbrechambfami,
       NULL::int AS nbrechambpmr,
       ouverture,
       ouvertureavecjours,
       ouverturedates,
       services,
       tel,
       NULL::varchar AS TYPE,
       NULL::varchar AS typelogements,
       url,
       'PIGMA'::text AS SOURCE,
       'https://www.pigma.org/portail/fr/jeux-de-donnees/aquitaine_residences_de_tourisme/info'::text AS source_url,
       geom
FROM public.residence_tourisme
UNION ALL
SELECT id,
       'Village vacance'::varchar AS TYPE,
       nomoffre,
       acces,
       acceshandi,
       activplace,
       animaux,
       chaines,
       clas,
       modgest,
       gestrsociale,
       commune,
       communeinsee,
       'Aquitaine'::varchar AS region,
       confort,
       cp,
       descriptifmob,
       equip,
       NULL::varchar AS formuleheb,
       groupe,
       groupemax::int,
       groupemin::int,
       labels,
       NULL::varchar AS labelsclas,
       localisation,
       mail,
       modpaiement,
       capa,
       capaclas,
       nbrelog::int,
       nbrelogclas::int,
       nbrelogpmr::int,
       NULL::int AS nbrelits,
       NULL::int AS nbrelitsclas,
       NULL::int AS nbrechamb,
       NULL::int AS nbrechambclas,
       NULL::int AS nbrechambfami,
       NULL::int AS nbrechambpmr,
       ouverture,
       ouvertureavecjours,
       ouverturedates,
       services,
       tel,
       typeheb,
       NULL::varchar AS typelogements,
       url,
       'PIGMA'::text AS SOURCE,
       'https://www.pigma.org/portail/fr/jeux-de-donnees/aquitaine_villages_de_vacances/info'::text AS source_url,
       geom
FROM public.villagevacance
UNION ALL
SELECT id::varchar,
       'Hébergements touristiques'::varchar AS TYPE,
       nom_offre,
       acces_nom,
       NULL::varchar AS acceshandi,
       NULL::varchar activplace,
       animaux_acceptes,
       chaines,
       categorie_classement,
       NULL::varchar AS modgest,
       NULL::varchar AS gestrsociale,
       commune,
       code_insee_commune::varchar,
       'Centre-Val de Loire'::varchar AS region,
       NULL::varchar AS confort,
       code_postal::varchar,
       NULL::varchar AS descriptifmob,
       equipements,
       NULL::varchar AS formuleheb,
       NULL::varchar AS groupe,
       NULL::int AS groupemax,
       NULL::int AS groupemin,
       labels,
       classement_labels,
       NULL::varchar localisation,
       NULL::varchar mail,
       NULL::varchar modpaiement,
       capacite_totale_en_nb_personnes,
       NULL::int AS capaclas,
       NULL::int nbrelog,
       NULL::int nbrelogclas,
       NULL::int nbrelogpmr,
       NULL::int nbrelits,
       NULL::int nbrelitsclas,
       nombre_total_chambres,
       NULL::int AS nbrechambclas,
       NULL::int nombre_chambres_familiale_2adultes_2enfants,
       nombre_chambres_acces_mobilite_reduite::int,
       NULL::varchar ouverture,
       NULL::varchar ouvertureavecjours,
       NULL::varchar ouverturedates,
       services_sur_place,
       telephone,
       type_bordereau,
       type_hebergement,
       site_web,
       'Région Centre-Val de Loire'::text AS SOURCE,
       'https://www.data.gouv.fr/fr/datasets/hebergements-touristiques-en-region-centre-val-de-loire/'::text AS source_url,
       geom
FROM public.cvl
UNION ALL
SELECT id::varchar,
       'Gite de groupe'::varchar AS TYPE,
       title,
       null::varchar as acces_nom,
       NULL::varchar AS acceshandi,
       NULL::varchar activplace,
       null::varchar as animaux_acceptes,
       null::varchar as chaines,
       null::varchar as categorie_classement,
       NULL::varchar AS modgest,
       NULL::varchar AS gestrsociale,
       ville,
       null::varchar as code_insee_commune,
       null::varchar AS region,
       NULL::varchar AS confort,
       null::varchar as code_postal,
       NULL::varchar AS descriptifmob,
       null::varchar as equipements,
       NULL::varchar AS formuleheb,
       NULL::varchar AS groupe,
       NULL::int AS groupemax,
       NULL::int AS groupemin,
       null::varchar as labels,
       null::varchar as classement_labels,
       NULL::varchar localisation,
       NULL::varchar mail,
       NULL::varchar modpaiement,
       capacite,
       NULL::int AS capaclas,
       NULL::int nbrelog,
       NULL::int nbrelogclas,
       NULL::int nbrelogpmr,
       NULL::int nbrelits,
       NULL::int nbrelitsclas,
       null::int as nombre_total_chambres,
       NULL::int AS nbrechambclas,
       NULL::int nombre_chambres_familiale_2adultes_2enfants,
       null::int as nombre_chambres_acces_mobilite_reduite,
       NULL::varchar ouverture,
       NULL::varchar ouvertureavecjours,
       NULL::varchar ouverturedates,
       null::varchar as services_sur_place,
       null::varchar as telephone,
       null::varchar as type_bordereau,
       null::varchar as type_hebergement,
       concat ('https://www.gitedegroupe.fr/','link')::text as url,
       'Gite de groupe'::text AS SOURCE,
       'https://www.gitedegroupe.fr/'::text AS source_url,
       geom
FROM public.gites)
SELECT nomoffre,
nature,
       
       commune,
       communeinsee,
       cp,
       region,
       acces,
       acceshandi,
       localisation,
       animaux,
       chaines,
       clas,
       modgest,
       gestrsociale,
       descriptifmob,
       confort,
       services,
       activplace,
       equip,
       formuleheb,
       typehco,
       typelogements,
       groupe,
       groupemax,
       groupemin,
       labels,
       labelsclas,
       capa,
       capaclas,
       nbrelogements,
       nbrelogclas,
       nbrelogpmr,
       nbrelits,
       nbrelitsclas,
       nbrechamb,
       nbrechambclas,
       nbrechambfami,
       nbrechambpmr,
       ouverture,
       ouvertureavecjours,
       ouverturedates,
       mail,
       modpaiement,
       tel,
       url,
       source,
       source_url,
       geom
FROM hebergements;

ALTER TABLE hebergements ADD COLUMN gid SERIAL PRIMARY KEY;
CREATE INDEX hebergements_gix ON hebergements USING GIST (geom);
